using System;
using System.Collections.Generic;

namespace ScriptDock.Models;

/// <summary>Live built-in values used whenever a config set has no stored copy.</summary>
public static class ConfigDefaults
{
    /// <summary>The launcher extension for the current platform: <c>.command</c> on macOS
    /// (and other Unix), <c>.ps1</c> on Windows.</summary>
    public static string DefaultExtension => OperatingSystem.IsWindows() ? ".ps1" : ".command";

    /// <summary>
    /// Built-in ignore patterns — regex matched against the full path — read when the set is absent. Their
    /// sole purpose is scan speed: skip the big auto-generated / downloaded trees of the languages
    /// this is used with (TypeScript/JavaScript, Python, C#, Rust), plus the universal <c>.git</c>,
    /// so a scan of a projects directory doesn't walk package and build output. They are deliberately
    /// NOT chosen to filter out "scripts that aren't yours" — doing so would risk hiding real ones;
    /// per-script exclusion is the Hide button's job. Editable by the user.
    /// </summary>
    public static IReadOnlyList<string> BuiltInIgnorePatterns { get; } =
    [
        "/node_modules/",   // TypeScript / JavaScript — downloaded packages
        "/\\.venv/",        // Python — virtual environment (downloaded packages)
        "/venv/",           // Python — virtual environment (alternate name)
        "/__pycache__/",    // Python — generated bytecode cache
        "/bin/",            // C# / .NET — build output
        "/obj/",            // C# / .NET — build output
        "/target/",         // Rust — build output and dependency cache
        "/\\.git/",         // any repo — VCS internals (large, never holds your scripts)
    ];
}
