using System;
using System.Collections.Generic;

namespace ScriptDock.Models;

/// <summary>
/// First-run defaults for <see cref="AppConfig"/>, applied only when no config file
/// exists yet (see <c>ConfigBootstrap</c>). Never applied to a merely-empty config — a
/// user who clears every extension or pattern has made a deliberate choice that must
/// survive a restart.
/// </summary>
public static class ConfigDefaults
{
    /// <summary>The launcher extension for the current platform: <c>.command</c> on macOS
    /// (and other Unix), <c>.ps1</c> on Windows.</summary>
    public static string DefaultExtension => OperatingSystem.IsWindows() ? ".ps1" : ".command";

    /// <summary>
    /// Built-in ignore patterns — regex matched against the full path — seeded on first run. Their
    /// sole purpose is scan speed: skip the big auto-generated / downloaded trees of the languages
    /// this is used with (TypeScript/JavaScript, Python, C#, Rust), plus the universal <c>.git</c>,
    /// so a scan of a projects directory doesn't walk package and build output. They are deliberately
    /// NOT chosen to filter out "scripts that aren't yours" — doing so would risk hiding real ones;
    /// per-script exclusion is the Hide button's job. Editable by the user.
    /// </summary>
    public static IReadOnlyList<string> BuiltInIgnorePatterns { get; } =
    [
        "/node_modules/",   // TypeScript / JavaScript — downloaded packages
        "/\\.venv/",        // Python — virtual environment (downloaded packages)
        "/venv/",           // Python — virtual environment (alternate name)
        "/__pycache__/",    // Python — generated bytecode cache
        "/bin/",            // C# / .NET — build output
        "/obj/",            // C# / .NET — build output
        "/target/",         // Rust — build output and dependency cache
        "/\\.git/",         // any repo — VCS internals (large, never holds your scripts)
    ];

    /// <summary>A config seeded for first run: the platform-default extension and the built-in ignore
    /// patterns. No root directory is seeded — the scan target is personal, so the user adds their own
    /// project root(s) in Settings rather than the app guessing a path.</summary>
    public static AppConfig CreateSeededConfig() => new()
    {
        Extensions = [DefaultExtension],
        IgnorePatterns = [.. BuiltInIgnorePatterns],
    };
}
